/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32L4x_gpio_driver.h"
#include "STM32L4x_spi_driver.h"
#include "STM32L4x_i2c_driver.h"
#include <string.h>

/* SPI NSSS PA4 AF5
 * SPI SCK  PA5 AF5
 * SPI MISO PA6 AF5
 * SPI MOSI PA7 AF5*/

/* I2C1 SCL PA9 AF4
 * I2C1 SDA PA10 AF4
 * I2C3 SCL	PA7	AF4
 * I2C3 SDA	PB4 AF4
 */

//uncomment this to test channel 3
#define CH3

I2C_Handle_t I2CHandle;
void I2C_GPIOInit(uint8_t channel);
void I2C_PinInits(uint8_t channel);

int main(void)
{


	uint8_t cmdCode = 0x50;
	uint8_t len;
	char rbuffer[30];

	#ifdef CH3
	I2C_GPIOInit(3);
	I2C_PinInits(3);
	I2C_PeripheralControl(I2C3,ENABLE);
	I2C_IRQITConfig(IRQ_NO_I2C3_EV,ENABLE);
	#else
	I2C_GPIOInit(1);
	I2C_PinInits(1);
	I2C_PeripheralControl(I2C1,ENABLE);
	I2C_IRQITConfig(IRQ_NO_I2C1_EV,ENABLE);
	#endif

	while(I2C_MasterSendDataIT(&I2CHandle,&cmdCode,1,0x62) != SUCCESS);
	while(I2C_MasterRecieveDataIT(&I2CHandle,&len,1,0x62) != SUCCESS);

	cmdCode = 0x51;
	while(I2C_MasterSendDataIT(&I2CHandle,&cmdCode,1,0x62) != SUCCESS);
	while(I2C_MasterRecieveDataIT(&I2CHandle,(uint8_t*)rbuffer,len,0x62) != SUCCESS);
	while(1);
}

void I2C_GPIOInit(uint8_t channel)
{
	GPIO_Handle_t I2CPins;
	if(channel == 1)
	{
		I2CPins.pGPIOx = GPIOA;
		I2CPins.GPIO_PinConfig.GPIO_Pinmode = GPIO_MODE_ALTFN;
		I2CPins.GPIO_PinConfig.GPIO_PinAltFn = 4;
		I2CPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD	;
		I2CPins.GPIO_PinConfig.GPIO_PinPuPdCtrl =  GPIO_PIN_PU;
		I2CPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPD_FAST;

		//SCL
		I2CPins.GPIO_PinConfig.GPIO_PinNumber = 9;
		GPIO_Init(&I2CPins);

		//SDA
		I2CPins.GPIO_PinConfig.GPIO_PinNumber = 10;
		GPIO_Init(&I2CPins);
	}
	else
	{
		I2CPins.pGPIOx = GPIOA;
		I2CPins.GPIO_PinConfig.GPIO_Pinmode = GPIO_MODE_ALTFN;
		I2CPins.GPIO_PinConfig.GPIO_PinAltFn = 4;
		I2CPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD	;
		I2CPins.GPIO_PinConfig.GPIO_PinPuPdCtrl =  GPIO_PIN_PU;
		I2CPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPD_FAST;

		//SCL
		I2CPins.GPIO_PinConfig.GPIO_PinNumber = 7;
		GPIO_Init(&I2CPins);

		//SDA
		I2CPins.pGPIOx = GPIOB;
		I2CPins.GPIO_PinConfig.GPIO_PinNumber = 4;
		GPIO_Init(&I2CPins);

	}
}


void I2C_PinInits(uint8_t channel)
{
	if(channel == 1)
	{
		I2CHandle.pI2Cx = I2C1;
	}
	else
	{
		I2CHandle.pI2Cx = I2C3;
	}
	I2CHandle.I2C_Config.I2C_PRESC = 0x01;
	I2CHandle.I2C_Config.I2C_SCLH = 0x61;
	I2CHandle.I2C_Config.I2C_SCLL = 0x63;
	I2CHandle.I2C_Config.I2C_SDADEL =0x01;
	I2CHandle.I2C_Config.I2C_SCLDEL =0x01;
	I2CHandle.I2C_Config.I2C_DeviceAddr=0x61;
	I2C_Init(&I2CHandle);
}



void I2C1_EV_IRQHandler(void)
{
	I2CReadStatusFlag(I2C1);
	if(getI2CFlag() == ADDRMATCH)
	{
		addressMatchEvent(I2C1);
	}

	else if (getI2CFlag() == RXEREADY)
	{
		recieverBufferFullEvent(&I2CHandle);
	}

	else if (getI2CFlag() == STOPBIT)
	{
		stopFlagEvent(&I2CHandle);
	}

	else if (getI2CFlag() == NACKF)
	{
		nackEvent(&I2CHandle);
	}

	else if (getI2CFlag() == TXISREADY)
	{
		transmitReadyEvent(&I2CHandle);
	}

}

void I2C3_EV_IRQHandler(void)
{
	I2CReadStatusFlag(I2C3);
	if(getI2CFlag() == ADDRMATCH)
	{
		addressMatchEvent(I2C3);
	}

	else if (getI2CFlag() == RXEREADY)
	{
		recieverBufferFullEvent(&I2CHandle);
	}

	else if (getI2CFlag() == STOPBIT)
	{
		stopFlagEvent(&I2CHandle);
	}

	else if (getI2CFlag() == NACKF)
	{
		nackEvent(&I2CHandle);
	}

	else if (getI2CFlag() == TXISREADY)
	{
		transmitReadyEvent(&I2CHandle);
	}
}
